# Generated by Django 3.1.3 on 2021-01-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20210125_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='bill_address1',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bill_address2',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bill_city',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bill_country',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bill_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bill_phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bill_state',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='bill_zipcode',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipp_address1',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipp_address2',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipp_city',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipp_country',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipp_name',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipp_phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipp_state',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='shipp_zipcode',
            field=models.CharField(max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='submitted_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
