# Generated by Django 3.1.5 on 2021-01-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(max_length=4)),
                ('esti_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('esti_no', models.CharField(max_length=10)),
                ('ref_no', models.CharField(max_length=10, null=True)),
                ('items', models.CharField(max_length=200)),
                ('quantitys', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('discount', models.CharField(max_length=100, null=True)),
                ('amount', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=50, null=True)),
                ('subtotal', models.CharField(max_length=10)),
                ('tax', models.CharField(max_length=3, null=True)),
                ('totalamount', models.CharField(max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
