# Generated by Django 3.1.5 on 2021-01-28 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20210125_1450'),
        ('estimate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='esti_date',
            field=models.CharField(max_length=10),
        ),
    ]
