# Generated by Django 3.1.3 on 2021-02-01 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estimate', '0002_auto_20210128_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='amount',
            field=models.CharField(max_length=33),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='discount',
            field=models.CharField(max_length=33, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='due_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='esti_date',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='items',
            field=models.CharField(max_length=33),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='price',
            field=models.CharField(max_length=33),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='quantitys',
            field=models.CharField(max_length=33),
        ),
    ]
