# Generated by Django 3.1.3 on 2021-02-01 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0004_auto_20210201_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_date', models.CharField(max_length=30)),
                ('due_date', models.CharField(max_length=30)),
                ('inv_no', models.CharField(max_length=10)),
                ('ref_no', models.CharField(max_length=10, null=True)),
                ('items', models.CharField(max_length=33)),
                ('quantitys', models.CharField(max_length=33)),
                ('price', models.CharField(max_length=33)),
                ('discount', models.CharField(max_length=33, null=True)),
                ('amount', models.CharField(max_length=33)),
                ('notes', models.CharField(max_length=50, null=True)),
                ('subtotal', models.CharField(max_length=10)),
                ('tax', models.CharField(max_length=3, null=True)),
                ('totalamount', models.CharField(max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
    ]
